apiVersion: apps/v1
kind: Deployment
metadata:
  name: flasktest-cy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasktest-cy
  template:
    metadata:
      labels:
        app: flasktest-cy
    spec:
      containers:
      - name: flasktest-microservice
        image: flasktest:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flasktest-service
spec:
  selector:
    app: flasktest-cy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer